// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZqp81pDkUogdGwrI4V4PcHNJKQWEXf30',
    appId: '1:122867977260:web:773300e367650750f2d589',
    messagingSenderId: '122867977260',
    projectId: 'fir-flutter-auth-51d98',
    authDomain: 'fir-flutter-auth-51d98.firebaseapp.com',
    storageBucket: 'fir-flutter-auth-51d98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAalm-AM2wkYcrclwnD9Yy0IzrC1dgzPMQ',
    appId: '1:122867977260:android:fa00d32612653080f2d589',
    messagingSenderId: '122867977260',
    projectId: 'fir-flutter-auth-51d98',
    storageBucket: 'fir-flutter-auth-51d98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjTwfQoQDqLioW_4ET2wu7uRdktN26x-4',
    appId: '1:122867977260:ios:53c1cfcde5fca8b5f2d589',
    messagingSenderId: '122867977260',
    projectId: 'fir-flutter-auth-51d98',
    storageBucket: 'fir-flutter-auth-51d98.appspot.com',
    iosClientId: '122867977260-tgp180mm7rm7fm09bbhnp5jc2f5no815.apps.googleusercontent.com',
    iosBundleId: 'com.example.arenamvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjTwfQoQDqLioW_4ET2wu7uRdktN26x-4',
    appId: '1:122867977260:ios:53c1cfcde5fca8b5f2d589',
    messagingSenderId: '122867977260',
    projectId: 'fir-flutter-auth-51d98',
    storageBucket: 'fir-flutter-auth-51d98.appspot.com',
    iosClientId: '122867977260-tgp180mm7rm7fm09bbhnp5jc2f5no815.apps.googleusercontent.com',
    iosBundleId: 'com.example.arenamvp',
  );
}
